### ISSUE TITLE
Creating child objects with non-unique URIs should be disallowed

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#127]
When creating child objects, it is currently possible to create objects with non-unique URIs as follows.  (This issue does not appear to affect `TopLevel` objects in the `Document`)
```
>>> cd = ComponentDefinition('cd')
>>> cd.sequenceAnnotations.create('sa')
<sbol.sequenceannotation.SequenceAnnotation object at 0x111bdf5d0>
>>> cd.sequenceAnnotations.create('sa')
<sbol.sequenceannotation.SequenceAnnotation object at 0x111bdf610>
>>> for ann in cd.sequenceAnnotations:
...     print(ann)
... 
http://examples.org/ComponentDefinition/cd/sa/1
http://examples.org/ComponentDefinition/cd/sa/1
```

**Comment by tcmitchell** [comment]
This works when the ComponentDefinition is in a Document, and fails when the ComponentDefinition is not in a Document. Add test cases for both.
