### ISSUE TITLE
Validate this new library works with SD2 infrastructure

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#13]
# To Do
* Nothing

# Done
| Name | Comments |
| ---- | ------ |
| sbh-adapter | Needs upload sub collections (#57) |
| sbol-dictionary-writer | does not use pySBOL |
| REDOER | does not use pySBOL |
| sbh-prospector | works |
| intent-parser| works |
| Robert Goldman's script | Works since #66 |
| etl-to-synbiohub-pipeline | Works as of 1.0 beta 5 |
| SYNBICT | Works as of 1.0 beta 5 |

**Comment by jakebeal** [comment]
List of all SD2 SBOL python-based infrastructure that needs testing, and its current status:
- sbol-dictionary-writer:		does not use pySBOL
- REDOER:				does not use pySBOL
- sbh-prospector:			working
- intent-parser:			working
- etl-to-synbiohub-pipeline:	3 failed tests
- sbh-adapter:			tests OK; needs write testing
- SYNBICT:				not yet tested
- Robert Goldman's script: not yet tested

**Comment by tcmitchell** [comment]
This work is complete as of 1.0 beta 5.
