### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#16]
[Python 2 end of life is January 1, 2020](https://www.python.org/doc/sunset-python-2/). There are just a few places where specific Python 2 compatibility is maintained.

```
$ grep -r version_info *
sbol/test/test_componentdefinition.py:        if sys.version_info[0] < 3:
sbol/test/test_componentdefinition.py:        if sys.version_info[0] < 3:
sbol/test/test_sequence.py:        if sys.version_info[0] < 3:
sbol/test/unit_tests.py.bak:#         # if sys.version_info[0] < 3:
sbol/test/unit_tests.py.bak:#         if sys.version_info[0] < 3:
sbol/test/unit_tests.py.bak:#         if sys.version_info[0] < 3:
```

We should eliminate these and declare that this SBOL python module is only compatible with Python 3.

**Comment by jakebeal** [comment]
Concur --- we have already made this decision for the SWIGed library as well.

**Comment by tcmitchell** [comment]
There's only one active use of `sys.version_info` at present:

```
$ grep -nr version_info sbol2 test
test/test_componentdefinition.py:84:        if sys.version_info[0] < 3:
```
