### ISSUE TITLE
Design: Should SBOL objects be hashable?

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#168]
In pySBOL objects like ModuleDefinitions are hashable. Objects are only equal if they are the identical object.

The argument for making SBOL objects hashable is backward compatibility. The hash value would be provided by the default `__hash__` method. We would have to remove our `SBOLObject.__eq__` implementation, because that is causing the `__hash__` method to be removed. (see https://docs.python.org/3.6/reference/datamodel.html#object.__hash__) I think this will mimic the behavior of pySBOL.

The argument against making SBOL objects hashable is that they are mutable. Mutable Python objects like `list` and `dict` are not hashable because they are mutable. This means the SBOL objects cannot be used as keys in dicts, nor can they be added to sets.

**Comment by bbartley** [comment]
I've never used an SBOL object's `__hash__` and don't know of any applications that use it.  It's not something I ever consciously implemented, and must be an artifact from SWIGification.

**Comment by jakebeal** [comment]
I would recommend that the object be hashable in terms of identity, but not in terms of contents.

My reasoning:
- I agree with @tcmitchell regarding mutability
- The URI of an object, however, is stable --- indeed, if one were to change the URI, in SBOL convention (inherited from RDF, irrc) that would be tantamount to changing to dealing with a different object.
- It's useful to be able to store stuff in hash tables / sets

**Comment by tcmitchell** [comment]
> I've never used an SBOL object's `__hash__` and don't know of any applications that use it. It's not something I ever consciously implemented, and must be an artifact from SWIGification.

The `__hash__` method is provided free to all classes as long as they do not implement `__eq__`. This is independent of SWIG. 

I had implemented `__eq__` which is why `__hash__` got taken away. We cannot implement a reasonable `__hash__` method for a mutable object. The contract of `__hash__` is that it return the same key over the life of the object. And `__hash__` should use the same attributes as those used to compute equality via `__eq__`.

So our choices are:
1. Implement `__eq__` (i.e. `==`) for SBOLObjects and lose hashability
2. Have hashability and lose the ability to test for equality using `==`. The `==` operator would instead test for identity.

pySBOL chose number 2 implicitly by not implementing `__eq__` for SBOLObjects.

**Comment by tcmitchell** [comment]
My read of @jakebeal's comment is that we should mimic pySBOL and choose number 2 above. That means leveraging the default `__hash__` method and the default `__eq__` method. 

We have the `SBOLObject.compare()` method to compare two objects for equality.

**Comment by tcmitchell** [comment]
The decision has been made to support hashing of `SBOLObject`s in the same way as pySBOL. That work will be done on #167
