### ISSUE TITLE
Pre-commit checks seem to be overlooking some style violations

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#219]
When running `pycodestyle . | wc -l`, it reports more style violations than the automated pre-commit checks.  I suspect this could be related to some recent changes in the project directory organization, and/or my local repo state.  Flagging it here, for a sanity check.

**Comment by bbartley** [comment]
Source of the problem identified.  I had build artifacts left over from building a package wheel.  This resulted in pycodestyle finding 2X as many style violations

**Comment by tcmitchell** [comment]
Your tree is likely out of date. The current version of the pre-commit hook only examines the `sbol2` and `test` directories. The problem you describe is one of the reasons it changed.
