### ISSUE TITLE
Setter/adder for hidden property fails in certain contexts

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#230]
When setting the `sequence` property the following test works fine:
```
# sequence and sequences should be synced up
cd = sbol2.ComponentDefinition('cd1', sbol2.BIOPAX_DNA)
seq = sbol2.Sequence('cd1_sequence', 'GCAT')
cd.sequence = seq
self.assertEqual([seq.identity], cd.sequences)
```
But, if you add the cd to a `Document`, then setting the `sequence` property doesn't work:
```
# now test whether this works in the context of a Document
doc = sbol2.Document()
cd = doc.componentDefinitions.create('cd1')
cd.sequence = seq
self.assertEqual([seq.identity], cd.sequences)
```
In fact, in this case,  `cd.sequence` returns `None`.  This behavior appears to result from the fact that `sequence` is a hidden property, and doesn't generalize to other type of singleton OwnedObject properties.

**Comment by tcmitchell** [comment]
It's not about hidden properties. When the ComponentDefinition is in a Document the add triggers [this code in OwnedObject.add()](https://github.com/SynBioDex/pySBOL2/blob/master/sbol2/property.py#L479-L482):

```python
        if sbol_obj.is_top_level() and self._sbol_owner.doc is not None:
            # Is this really all we need to do?
            self._sbol_owner.doc.add(sbol_obj)
            return
```

Clearly that's not _all_ we need to do. How is it supposed to work? The method is pretty clearly divided into is-top-level and is-not-top-level. Is that a valid distinction here?

**Comment by tcmitchell** [comment]
On further reflection and reading the SBOL 2.3 spec (dated April 1, 2019), it looks like the sequence attribute on a ComponentDefinition should not exist as currently cast. `Sequence` is a `TopLevel` (sec 7.6) and "_TopLevel objects are not nested inside any other object via a composite aggregation or black diamond arrow association property_" (sec 7.5).

While I think the code may still have bugs, I don't think we should be implementing a special workaround for the legacy ComponentDefinition.sequence attribute. It is no longer defined in the spec, having been converted to ComponentDefinition.sequences (a ReferencedObject). 

Can we instead make `sequence` an attribute on ComponentDefinition that is not an OwnedObject, but rather just a veneer over `sequences`? On access it could convert the first sequence in `sequences` to an object through searching the document, returning it if found, and raising an error if not found. And on set it could add the sequence to the Document and make the `sequences` attribute be `[sequence.identity]` (or is it `[sequence.persistentIdentity]`?)

I'm open to other suggestions about how to handle `ComponentDefinition.sequence` for backward compatibility. We just want to be careful not to run afoul of the spec and put a lot of band-aids in for this one case.
