### ISSUE TITLE
Implement PartShop advanced search

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#240]
`PartShop.search` supports "general search" and "exact search". Add "advanced search" using a `SearchQuery` object akin to pySBOL. In PartShop.search, add appropriate code to dispatch to `PartShop.search_advanced` before the dispatch to `search_general` and `search_exact`.

Also, update the `typing` info to support passing a `SearchQuery` as the `search_text` argument.

**Comment by JMante1** [comment]
Based on my understanding of this milestone it would be very helpful to the GSoC submit plugin if this was implemented relatively soon as we would like to be able to extract parts from a synbiohub collection based on the title/displayId.

**Comment by tcmitchell** [comment]
@JMante1 Thanks for the feedback. I have moved this issue back to 1.1. Can you add one or more sample searches that you'd like to do? That will help us to develop and test this feature. The more examples, the better.

**Comment by JMante1** [comment]
Example 1:
- Expected return: https://synbiohub.org/public/igem/BBa_E0040/1 (though potentially other parts could exist if the exact match is not unique)
-What we will have is the collection: https://synbiohub.org/public/igem/igem_collection/1 and that it must be a DNARegion type
- And "GFP" (the dcterms:title) or "BBa_E0040" (the displayID) we won't necessarily know whether the string we have is the title or displayID but are happy to do two searches e.g. title="GFP" and displayID="GFP". We do only want parts whose full title/displayID is equal to GFP and not ones that contain GFP such as: https://synbiohub.org/public/igem/BBa_K1852000/1

Example 2:
- Looking for: https://synbiohub.org/public/igem/BBa_R0010/1 and/or https://synbiohub.org/public/igem/BBa_C0012/1
- Collection: https://synbiohub.org/public/igem/igem_collection/1
- Search term: "LacI"
- Don't want: https://synbiohub.org/public/igem/BBa_S03334/1 or https://synbiohub.org/public/igem/BBa_K1444015/1

Example 3:
- Looking for: https://synbiohub.org/public/igem/BBa_R0010/1
- Collection: https://synbiohub.org/public/igem/igem_collection/1
- Search term: "BBa_R0010"
- Don't want: https://synbiohub.org/public/igem/BBa_S03334/1 or https://synbiohub.org/public/igem/BBa_K1444015/1 

Example 4:
- Looking for: https://synbiohub.org/public/igem/BBa_B0034/1
- Collection: https://synbiohub.org/public/igem/igem_collection/1
- Search term: "BBa_B0034"
- Don't want:  https://synbiohub.org/public/igem/BBa_I13617/1

Example 5:
- Looking for: https://synbiohub.org/public/bsu/BO_28874/1
- Collection: https://synbiohub.org/public/bsu/bsu_collection/1
- Search term: "acca"
- Don't want: https://synbiohub.org/public/bsu/BO_26604/1

Example 6:
- Could something like the above examples be done given a private collection like: https://synbiohub.org/user/UserName/Mine_alone/Mine_alone_collection/1

**Comment by tcmitchell** [comment]
@JMante1 That's about as good a list of test cases as I've ever seen. Thanks very much for the time you took to enumerate these, and especially for noting what you don't want  in addition to what you do want. This should help us to implement the feature properly. I'll let you know when there is something for you to try.

**Comment by bbartley** [comment]
@JMante1 is there any value in being able to save the search parameters for a given search operation (e.g., for purposes of automating analyses)?

**Comment by JMante1** [comment]
@tcmitchell thank you so much, I look forward to testing it. @bbartley could you give an example of what you mean by saving the search parameters?

**Comment by bbartley** [comment]
@JMante1 all of your search examples above are described in natural language;  would it be helpful to be able to capture a search query in machine readable format so you could reproduce that search at a later time?  or keep a record of which searches you have done?

**Comment by JMante1** [comment]
@bbartley Yes that would be a nice feature to have, but it isn't something we are looking for in the first use case of the exact search.

**Comment by JMante1** [comment]
@tcmitchell I was wondering what kind of error message you intend to display if a query is made and the part doesn't exist?

**Comment by tcmitchell** [comment]
@JMante1 The `PartShop.search` method will always return a list if the search was successful. The list will be empty if the part does not exist. This is not an error condition, so no error message is returned. An empty list indicates that the search completed successfully and there were no matching entries.

If the query itself results in an error from SynBioHub then an `SBOLError` will be raised with error_code `SBOLErrorCode.SBOL_ERROR_BAD_HTTP_REQUEST`.

**Comment by tcmitchell** [comment]
@JMante1 (and @bbartley ) I don't see an ability to do case-insensitive search in the [SynBioHub API](https://synbiohub.github.io/api-docs/#search-metadata). @JMante1 if you know how to invoke case-insensitive search via the SynBioHub API, I'll be happy to implement that. For now I'm doing what SynBioHub allows via the published API.

**Comment by JMante1** [comment]
@tcmitchell can do a case insensitive search using the sparql endpoitn: filter (regex(?title, 'accA', "i"))  is case insensitive (uses the "i" flag as specified by sparql regex which follows: https://www.w3.org/TR/xpath-functions/#flags). Thank you for clarifying the errors and empty list. Thank you for being so quick to implement the search, would you be able to add an example of how to use it to complete one of the examples I provided?

**Comment by tcmitchell** [comment]
@JMante1 `PartShop.search()` does not call the [`sparql`](https://synbiohub.github.io/api-docs/#sparql-query) endpoint at SynBioHub. Instead it calls the [`search`](https://synbiohub.github.io/api-docs/#search-metadata) endpoint. If you want to use SPARQL to do case insensitive search you'll want to use `PartShop.sparqlQuery()`.

As far as I can tell, the SynBioHub [`search`](https://synbiohub.github.io/api-docs/#search-metadata) endpoint does not allow case insensitive search of attributes as you seem to be requesting. For instance, in your example 5 above, you want to search for a dcterms:title of "acca", and have that match "accA" in https://synbiohub.org/public/bsu/BO_28874/1. That won't work via `PartShop.search()` because the SynBioHub [`search`](https://synbiohub.github.io/api-docs/#search-metadata) endpoint doesn't allow specifying case independent search of attributes like dcterms:title.

For example code, please look at the unit tests in `test/test_searchquery.py` which cover all 5 of your use cases within the bounds of `PartShop.search()` capability.
