### ISSUE TITLE
SYNBICT unit tests are very slow

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#244]
The SYNBICT unit tests take more than 4 times longer with sbol2 than they do with pysbol.

The slowness seems to be centered around removal of objects. SYNBICT removes over 4,000 annotations. On each removal the entire document is searched for the URI being removed. [The block of code](https://github.com/SynBioDex/pySBOL2/blob/4e59b5e411e4dc53083a78bd6ea98c7b0b4d05af/sbol2/property.py#L777-L779) says "Erase nested, hidden TopLevel objects from Document".

First off, the code looks like it is implemented incorrectly. The same [block in libSBOL](https://github.com/SynBioDex/libSBOL/blob/50fb77cec1b043ede08ed315cfac6958e80b9d2f/source/document.h#L1565-L1567) says if the URI is _not_ found, but the sbol2 code says if not None, or _is_ found.

Secondly, what does this code actually do? It looks like if the URI is not found, then the object's doc attribute is set to None. This runs after the object was removed from the Document. Do we need this code?

Removing the code for the SYNBICT test makes them run about 9 times faster than when the code is in place.

**Comment by bbartley** [comment]
I think this clause is such that if the user does `component_def.sequence.remove(uri)` it will also remove the object from `document.sequences`.

Not sure if the inverse is true, such that `doc.sequences.remove(uri)` also removes the object from `component_def.sequence`.

I will dig into this.
