### ISSUE TITLE
Properties with no defined value appear in getProperties(): backwards compatibility issue

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/pySBOL2#255]
In the SynBioHub instance that is operated by the DARPA SD2E program, I have this entity, a `FunctionalComponent`: `https://hub.sd2e.org/user/sd2e/design/UWBF_24962_Network/beta_estradiol/1`

If I try to pull its title (`http://purl.org/dc/terms/title`) property using the `getPropertyValue` method, I get an index out of bounds error, because the property has the value `[]`.

This code used to work, because I protected it with `TITLE_PROP in self.getProperties()` and this would return `False` if `getPropertyValue` would error out, but that is no longer the case.

**Comment by tcmitchell** [comment]
Here is a small code example for use in a unit test:

```python
>>> import sbol2
RDFLib Version: 5.0.0
>>> fc = sbol2.FunctionalComponent()
>>> fc.getPropertyValue(sbol2.SBOL_NAME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tommy/sd2/pySBOL2/sbol2/object.py", line 286, in getPropertyValue
    return values[0]
IndexError: list index out of range
```

**Comment by tcmitchell** [comment]
In pysbol `SBOLObject.getPropertyValue` always returns a string. So if the property is an IntProperty, it still returns a string:

```python
>>> c = sbol.Cut()
>>> c.getPropertyValue(sbol.SBOL_AT)
'0'
```

This should be easy to fix by checking for the length of the property list and returning an empty string if the list is empty, otherwise dereferencing the list and converting to string.
