### ISSUE TITLE
Improve documentation for installing pySBOL2 on mac

### ISSUE THREAD

**Issue by IsabelMarleen** [SynBioDex/pySBOL2#258]
When installing pySBOL2 on my mac, I received the error message that it wasn't compatible with my python version. I was then able to identify the problem, which was that pySBOL doesn't support python 2, which is preinstalled on mac and part of the operating system, and even after I had installed python 3, it was necessary to specify which python version the computer was supposed to use. 
I am aware of the section in the documentation "If you have trouble importing the module with the setup script, check to see if there are multiple Python installations on your machine and also check the output of the setup script to see which version of Python is the install target.", but I suggest adding that on mac there are necessarily two python versions installed and how to specify python 3.

**Comment by tcmitchell** [comment]
Thanks for the feedback and sorry for the trouble. Since Python 2 is no longer supported we made a decision to be compatible only with Python 3 for this new modules. I'm glad you were able to get it working.
