### ISSUE TITLE
AttributeError: module 'packaging.version' has no attribute 'NegativeInfinity'

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#290]

**Comment by bbartley** [comment]
Upgrading the package from 19.1 to 20.4 seemed to resolve this.  Do we need to specify a minimum version for the packaging dependency in the `setup.py` file?
```
"Installing collected packages: packaging
  Attempting uninstall: packaging
    Found existing installation: packaging 19.1
    Uninstalling packaging-19.1:
      Successfully uninstalled packaging-19.1
Successfully installed packaging-20.4
```

**Comment by tcmitchell** [comment]
`setup.py` has a dependency on packaging version 20 or higher as of commit a5e5253. Is it possible your tree is not up to date?

```
            'packaging>=20.0'
```
