### ISSUE TITLE
RDF predicate for Measurement.unit is incorrect

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#304]
Current predicate `http://sbols.org/v2#unit` should be `http://sbols.org/v2#hasUnit`

**Comment by tcmitchell** [comment]
The test file [test/SBOLTestSuite/SBOL2/Measure.xml](https://github.com/SynBioDex/SBOLTestSuite/blob/master/SBOL2/Measure.xml#L19) shows a URI of `http://www.ontology-of-units-of-measure.org/resource/om-2/hasUnit`. The same is true for `hasNumericalValue`. I don't see an indication in the [spec](https://sbolstandard.org/wp-content/uploads/2016/06/SBOL2.3.0.pdf) of which namespace these names (`hasUnit`, `hasNumericalValue`) are supposed to have. Perhaps it resides somewhere in the front matter?

libSBOLj uses the ontology of units of measure namespace for `hasUnit` and `hasNumericalValue`. libSBOLj also uses different nomenclature. An `Interaction` has `measures` (not `measurements`) and each element of `measures` is a `Measure`, not a `Measurement`. See https://github.com/SynBioDex/libSBOLj/blob/master/core2/src/main/java/org/sbolstandard/core2/Sbol2Terms.java#L284 for starters.

And it looks like these are new in SBOL 2.3.0, so perhaps we are simply out of date with the specification. I think more discussion is warranted before making any changes. I think the needed change is broader than this issue might indicate.
