### ISSUE TITLE
`Document.get` should implement same behavior as `Document.getExtensionObject`

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#316]
Similar to how `Document.addExtensionObject` delegates to `Document.add`, I propose that `get` should delegate to `getExtensionObject`.  (Or perhaps the delegation roles should be reversed.)

I would then propose to deprecate `getExtensionObject` and `addExtensionObject` in favor of the more concise method names.

**Comment by jakebeal** [comment]
If this looks like it will take more than about 15 minutes, then push it back to 1.1
