### ISSUE TITLE
Validate this new library works with CRISPR_example.py

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#34]
Another test script for validating SBOL core functionality is here:

https://github.com/SynBioDex/libSBOL/blob/master/wrapper/CRISPR_example.py

This may be the best script for evaluating coverage of the core data model.

**Comment by tcmitchell** [comment]
As of [1.0 beta 2](https://github.com/SynBioDex/pySBOL2/milestone/4) [CRISPR_example.py](https://github.com/SynBioDex/libSBOL/blob/master/wrapper/CRISPR_example.py) runs cleanly. 

We need to verify that the output matches between [pySBOL](https://github.com/SynBioDex/pySBOL) and sbol2. That means using RDF comparison as is done in the second half of the round trip tests, in addition to sbol/sbol2 Document comparisons.

**Comment by tcmitchell** [comment]
The output of CRISPR_example.py should match `test/SBOLTestSuite/SBOL2/RepressionModel.xml`
