### ISSUE TITLE
Rdflib Error in gene_cassette.py Example

### ISSUE THREAD

**Issue by IsabelMarleen** [SynBioDex/pySBOL2#342]
#### Description
Running the gene_cassette.py file leads to the error:

>  Object http://sys-bio.org/ComponentDefinition/gene_example/R0010_0/1 must be an rdflib term

 and no .xml file can be written.
#### Files
https://github.com/SynBioDex/pySBOL2/blob/master/examples/gene_cassette.py

**Comment by tcmitchell** [comment]
@IsabelMarleen Sorry about that. `gene_cassette.py` was just added yesterday. The bug you report here was filed as #319 and fixed in #327. You can either [install from source](https://pysbol.readthedocs.io/en/latest/installation.html#using-python) or wait for the next release which should be next week.

**Comment by JMante1** [comment]
Hi, I ran the gene_cassette.py example (having installed from source) and now run into the error: 

`
  File "C:\example.py", line 27, in <module>
    gene.assemblePrimaryStructure([r0010, b0032, e0040, b0012])

  File "C:\sbol2\componentdefinition.py", line 324, in assemblePrimaryStructure
    primary_structure = self.assemble(primary_structure, assembly_method, doc)

  File "C:\\sbol2\componentdefinition.py", line 269, in assemble
    raise TypeError('Invalid component_list specified. Please provide a list '

TypeError: Invalid component_list specified. Please provide a list of ComponentDefinitions or, alternatively, a list of ComponentDefinition displayIds
`

**Comment by tcmitchell** [comment]
Hi @JMante1 can you please attach your `example.py` to this issue so that we can help you to debug this issue? Thanks!

**Comment by JMante1** [comment]
Sorry in rerunning it it worked fine. I suspect that I forgot to restart the IDE after having updated the pysbol2. Thank you.

**Comment by tcmitchell** [comment]
This appears to be working as expected.
