### ISSUE TITLE
Parent-child extensions are not serialized properly

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#350]
The following example defines two extension classes related by a parent-child compositional relationship.  However, when parent-child objects are instantiated and serialized, both the parent and child are serialized as top level objects in the XML. 
```
class DataSheet(sbol2.Identified):

    RDF_TYPE = 'http://examples.org#DataSheet'

    def __init__(self, uri='example'):
        super().__init__(uri=uri,
                         type_uri=DataSheet.RDF_TYPE)

class Analysis(sbol2.TopLevel):

    RDF_TYPE = 'http://examples.org#Analysis'

    def __init__(self, uri=None, model=None):
        super().__init__(uri=uri,
                         type_uri=Analysis.RDF_TYPE)
        self.model = sbol2.ReferencedObject(self, sbol2.SBOL_MODELS, sbol2.SBOL_MODEL,
                                            0, 1, [])
        self.dataSheet = sbol2.OwnedObject(self, 'http://examples.org#dataSheet',
                                           DataSheet, '0', '1', [])

doc = sbol2.Document()
analysis = Analysis('foo')
doc.add(analysis)
analysis.dataSheet = DataSheet('foo')
print(doc.writeString())
```
This is serialized as:
```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:sbol="http://sbols.org/v2#" xmlns:ns0="http://examples.org#">
  <ns0:Analysis rdf:about="http://examples.org/Analysis/foo/1">
    <sbol:persistentIdentity rdf:resource="http://examples.org/Analysis/foo"/>
    <sbol:version>1</sbol:version>
    <ns0:dataSheet rdf:resource="http://examples.org/Analysis/foo/foo/1"/>
    <sbol:displayId>foo</sbol:displayId>
  </ns0:Analysis>
  <ns0:DataSheet rdf:about="http://examples.org/Analysis/foo/foo/1">
    <sbol:displayId>foo</sbol:displayId>
    <sbol:persistentIdentity rdf:resource="http://examples.org/Analysis/foo/foo"/>
    <sbol:version>1</sbol:version>
  </ns0:DataSheet>
</rdf:RDF>
```

**Comment by tcmitchell** [comment]
This is a limitation of `sbol2/SBOL2Serialize.py`, which comes from [pysbolgraph](https://github.com/udp/pysbolgraph).

The `is_ownership_relation` function in `SBOL2Serialize.py` hardcodes all of the possible ownership relations in SBOL2. Your new ownership relationship, "http://examples.org#dataSheet", is not in the set, and thus does not get serialized as an ownership relation.

As currently constructed, the set of ownership relations is not extensible. Even if it were, it's not clear how a user would know that they need to extend the list based on their extension class(es).

If I reach in manually to add "http://examples.org#dataSheet" to the known set of ownership relations, `SBOL2Serialize.py` does serialize the classes in a nested fashion as desired.
