### ISSUE TITLE
Why does config use string values of enumerations?

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#36]
The configuration (see config.py, Config.getOption(), etc.) uses the ConfigOptions `.value` under the covers. Why not just use the ConfigOptions themselves?

`Config.getOption(ConfigOptions.SBOL_COMPLIANT_URIS.value)` would become `Config.getOption(ConfigOptions.SBOL_COMPLIANT_URIS)`, which seems more intuitive.

Why am I asking? Because this was the source of a bug where code did not have the `.value` suffix and was failing without an exception, so kind of silently. Using strings also allows users to rely on strings for core configuration options, which lends itself to typos and forced backward compatibility of what should be internal values.

**Comment by bbartley** [comment]
In the SWIGged library, it was expedient for Config options to use string values because sometimes these values got passed directly as options to the raptor RDF parser library and sometimes they are passed directly as POST parameters to REST API calls.  (And because I was a noob and didn't think very hard about doing it a better way.  So if there's a better way we should do it)

**Comment by tcmitchell** [comment]
Perhaps we can set up some test cases and thus understand what the constraints are on the Config options. Then we could make an informed decision about whether to switch or keep it as is and document why.

**Comment by bbartley** [comment]
BTW the SWIGged library has a safeguard.  For each configuration parameter it maintains a list of allowed values.  So if a user enters an incorrect value or typo, it will throw an error, and the error message will provide the user with a list of valid options

**Comment by jakebeal** [comment]
Next step: see if existing code uses .value, and make a decision.

**Comment by tcmitchell** [comment]
Both `Config.getOption` and `Config.setOption` will accept a `ConfigOptions` instance or a string. Let's at least always use a ConfigOptions.SOMETHING in the library instead of a string. That will set a good example for users of the library. Here are grep commands that will identify places where a string is passed when a defined constant should be used:

```shell
grep getOption sbol2/*.py | grep -v ConfigOptions

grep setOption sbol2/*.py | grep -v ConfigOptions
```

There are 10 places where we pass a string to getOption, and 1 where we pass a string to setOption.

Notably, there is a case where we call setOption with a string in `examples/CRISPR_example.py`. Let's set a good example and not do that.

**Comment by tcmitchell** [comment]
Ugh. Strings were used in code, tests, examples, and documentation. Everywhere. A pandemic of constant avoidance. Use the constants!
