### ISSUE TITLE
Merging of Documents with `append` is broken

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#362]
The `append` method should merge RDF graphs and update SBOL Documents accordingly.  Currently, some data and objects in the SBOL Document tree are being duplicated when merging.  This is strange, because RDFlib eliminates redundant triples when merging graphs (it takes the union of the triples).  So duplication of objects and property values should not occur.

The following results in an Assertion error due to duplication of values/objects:
```
CRISPR_LOCATION = 'crispr_example.xml'
doc = sbol2.Document()
doc.read(CRISPR_LOCATION)
old_doc_len = len(doc)
cd_uri = 'http://sbols.org/CRISPR_Example/gRNA_b/1.0.0'
cd = doc.componentDefinitions['http://sbols.org/CRISPR_Example/gRNA_b/1.0.0']
c = cd.components.create('c')
old_component_len = len(cd.components)
doc.write('foo.xml')
doc.append('foo.xml')
cd = doc.componentDefinitions[cd_uri]
assert(len(cd.components) == old_component_len)
assert(len(doc) == old_len)
```

**Comment by tcmitchell** [comment]
`TestDocumentExtensionObjects.test_idempotent_read` is incredibly similar to this test, and it passes. The difference is the creation of a `Component` in the `ComponentDefinition`. The overall length of the document in this test remains the same, but the length of the ComponentDefinition's components changes on the append.
