### ISSUE TITLE
test_roundtrip has lots of differences in RDF

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#38]
`test_roundtrip.py` compares the RDF after the roundtrip, and finds lots of differences. These are reported by default like this:

```
WARNING:sbol.test:Detected 24 differences in RDF
WARNING:sbol.test:Set environment variable SBOL_TEST_DEBUG to see details
```

To see the details run with the SBOL_TEST_DEBUG environment variable set (to any value), like this:

```shell
SBOL_TEST_DEBUG= python3 -m unittest sbol/test/test_roundtrip.py
```

**Comment by bbartley** [comment]
Have scanned through the RDF diffs.  These errors all relate to either #43 or #7.

**Comment by tcmitchell** [comment]
Remaining issues involve extensions, see #7

**Comment by tcmitchell** [comment]
These issues have been reduced to 3, and all are related to the `version` property.
