### ISSUE TITLE
Sequence Ontology resolution

### ISSUE THREAD

**Issue by dr3y** [SynBioDex/pySBOL2#383]
Hi I am trying to read SBOL files and I have come across an annoying feature of annotation. Sometimes parts have a `role` which is a `plasmid` and sometimes as a `plasmid_Vector`. This shouldn't be a problem because SequenceOntology.org knows that a `plasmid_vector` is a type of `plasmid`. However, what you can get from an SBOL file is a string like `http://identifiers.org/so/SO:0000755`, and so any code that tries to understand this has to know that that string means `plasmid_vector` which is functionally the same as `plasmid`.

Do you have any recommended way of doing this "Ontology Resolution" in python? How can one reliably know that a `ComponentDefinition` has a role compatible with `Promoter` (for example) in a reliable way?

**Comment by jakebeal** [comment]
This isn't exactly a pySBOL issue, but more a general question of how to work with ontologies in python. There are a lot of different ways to go about this, and you might find some of the [tutorials and resources on OBOFoundry](http://www.obofoundry.org/resources) useful.  Of the various approaches, it seems like the https://pypi.org/project/Owlready2/ library is one of the preferred routes, if you're OK with holding the ontology locally, while SPARQL with Ontobee (http://www.ontobee.org/) seems better if you want to use them via a live online source.

**Comment by jakebeal** [comment]
@dr3y Has your question been resolved? If so, I will close this issue.

**Comment by bbartley** [comment]
@dr3y We are working on a project here that may help with this issue.  See https://github.com/SynBioDex/Owlet
