### ISSUE TITLE
VariableComponent objects not created

### ISSUE THREAD

**Issue by ImperialiGEM2020** [SynBioDex/pySBOL2#385]
I noticed that the variableComponent property of the CombinatorialDerivation class is creating OwnedObjects of type SBOLObject instead of VariableComponent as expected.

The following fixes should correct the error:
- Add `URIRef(SBOL_VARIABLE_COMPONENT): VariableComponent` to `Config.SBOL_DATA_MODEL_REGISTER` (and import `VariableComponent` from `.combinatorialderivation`) in `document.py`
- Correct typos in `constants.py`
    - `SBOL_VARIANT_DERIVATIONS = SBOL_URI + "#variantDeriviations"` ➡️ `SBOL_VARIANT_DERIVATIONS = SBOL_URI + "#variantDerivation"`
    - `SBOL_VARIANTS = SBOL_URI + "#variants"` ➡️  `SBOL_VARIANTS = SBOL_URI + "#variant"`
    - `SBOL_VARIANT_COLLECTIONS = SBOL_URI + "#variantCollections"` ➡️ `SBOL_VARIANT_COLLECTIONS = SBOL_URI + "#variantCollection"`

**Comment by tcmitchell** [comment]
Good catches, thanks for reporting. I found some test cases that I was able to use to verify the issue(s). #387 has fixes, and I'll add unit tests as well.

**Comment by tcmitchell** [comment]
@ImperialiGEM2020 Thanks again for the bug report. This has been fixed. To get the fixes now, without waiting for a release, you should be able to do this:

```shell
pip install -U git+https://github.com/synbiodex/pysbol2
```

If you need further assistance you can reopen this issue or create a new issue.
