### ISSUE TITLE
PythonicInterface class is missing

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#395]
pysbol [defines a `PythonicInterface` class](https://github.com/SynBioDex/libSBOL/blob/50fb77cec1b043ede08ed315cfac6958e80b9d2f/wrapper/libsbol.i#L1561) that is used by a project when defining an extension. There is no `PythonicInterface` class in pySBOL2, so it is not compatible with programs that use `PythonicInterface`.

Should `PythonicInterface` be added? If so, what functionality does it provide and who can it be properly tested for compatibility?

Was pysbol's `PythonicInterface` intended for use in programs/libraries? Was it necessary when defining extensions?

**Comment by bbartley** [comment]
The `PythonicInterface` is obsolete and isn't needed.  This was a contrivance for SWIG pySBOL, but in fact, it is now obsolete even for SWIG-pySBOL.  Before I figured out a cleaner way to do it, I used this mix-in class to convert the SWIG-like behavior of extension objects into something more Pythonic.
