### ISSUE TITLE
Unable to create SequenceConstraint objects

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioDex/pySBOL2#440]
It looks like the SequenceConstraint class is not accessible because it hasn't been added to the __init__.py file for sbol2. 

Steps to recreate this issue:

```
import sbol2

constraint1 = sbol2.SequenceConstraint('loxP1_to_CDS', loxP1.identity, cds.identity, sbol2.SBOL_RESTRICTION_PRECEDES)

```
This throws an error: 

`AttributeError: module 'sbol2' has no attribute 'SequenceConstraint'`

**Comment by jakebeal** [comment]
Fixed by #443
