### ISSUE TITLE
Optimize serialization and parsing performance on large SBOL files

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#8]
Large SBOL files (including some in the round-trip test suite) currently bog down during serialization and parsing.  There are optimizations for this implemented in libSBOL which should be ported over to this new library.

**Comment by jakebeal** [comment]
A large genome to test against also: https://hub.sd2e.org/user/sd2e/design/W303/1

**Comment by tcmitchell** [comment]
An exploration revealed that [RDFlib](https://github.com/RDFLib/rdflib) takes more than half of our file loading time. We simply cannot go any faster than that, and that is 2x - 4x longer than pySBOL's loading which uses [Raptor](http://librdf.org/raptor/). We have implemented some of the optimizations used in libSBOL, and tried some others that did not yield any performance improvements.

I think we've done what we can reasonably do on this. It's possible we may need to revisit this topic in the future.

**Comment by jakebeal** [comment]
Is there any way to use Raptor with pySBOL3 without reopening the entire horrible cross-platform can of worms?
