### ISSUE TITLE
Unsetting of Property values should be supported

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#93]
A number of idioms for unsetting or clearing property values are not currently supported.  For example:
```
>>> cd = ComponentDefinition
>>> cd.name = 'foo'
>>> cd.name = None
>>> print(cd.name)
foo
```
Similarly, assigning an empty string to a property value should be equivalent to assigning None.  (As a standard practice, SBOL tools and many RDF tools do not serialize triples with empty Literal values):
```
>>> cd = ComponentDefinition
>>> cd.name = 'foo'
>>> cd.name = ''
>>> assert(cd.name == None)
```
Finally, the following idiom for unsetting properties with lists of values should also be supported:
```
plasmid.roles = [SO_PLASMID, SO_CIRCULAR]
plasmid.roles = []
assert(len(plasmid.roles) == 0)
```

**Comment by tcmitchell** [comment]
I agree with the first and third cases above, and I disagree with the middle case. As specified above, the middle case is:

```python
>>> cd = ComponentDefinition
>>> cd.name = 'foo'
>>> cd.name = ''
>>> assert(cd.name == None)
```

As a programmer I would be shocked and dismayed to find that the name attribute's value is None in the last line. I set it to the empty string, and I expect the value to be the empty string. Like this:

```python
>>> cd = ComponentDefinition
>>> cd.name = 'foo'
>>> cd.name = ''
>>> assert(cd.name == '')
```

`None` and `''` are two different things in Python. Witness:

```python
>>> '' == None
False
>>> '' is None
False
```

I know of no cases, and no idioms, where setting something in Python to the empty string results in the value being converted to None. If there is such a case or idiom, please enlighten me.

**Comment by tcmitchell** [comment]
Case #1 above is now supported via #91 and #95.

```python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sbol
INFO:rdflib:RDFLib Version: 4.2.2
>>> cd = sbol.ComponentDefinition()
>>> cd.name
>>> cd.name = 'foo'
>>> cd.name
rdflib.term.Literal('foo')
>>> print(cd.name)
foo
>>> 
>>> 
>>> cd.name = None
>>> cd.name
>>> print(cd.name)
None
```

**Comment by bbartley** [comment]
> I know of no cases, and no idioms, where setting something in Python to the empty string results in the value being converted to None. If there is such a case or idiom, please enlighten me.

This is not a Python idiom -- it's an SBOL idiom.  SBOL libraries and serialization do not distinguish between empty string and null.  See this conversation on the SBOL developers list: 
https://groups.google.com/forum/#!msg/sbol-dev/r95K7mtkEGU/2KJMNKZWBQAJ

**Comment by jakebeal** [comment]
It seems like maybe this should be revisited at some point...

**Comment by bbartley** [comment]
#123 fixes this issue for ReferencedObject type attributes.  However, it remains an issue for URIProperty and perhaps other attribute types.
