### ISSUE TITLE
Create Float, DateTime, and Version properties

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL2#96]
LiteralProperty should become an abstract base class. IntProperty, FloatProperty, DateTimeProperty, and VersionProperty should define or override the `convert_to_user` and `convert_from_user` methods.

@bbartley says version numbers are derived from [Maven version numbers](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400), so we'll have to come up with a reasonable way to validate those. Or just let the user figure out it.

**Comment by bbartley** [comment]
`sbol.test.test_identified.TestCopy.test_copy_and_increment_version` on  branch 71-implement-copy-methods is currently marked as an expected failure because it depends on `VersionProperty.incrementMajor` method

**Comment by tcmitchell** [comment]
`IntProperty` exists. FloatProperty, DateTimeProperty, and VersionProperty still need to be implemented.

**Comment by tcmitchell** [comment]
Closed by #296
